openapi: 3.1.0

info:
  title: CasaOS Hello World API
  version: v2

servers:
  - url: /v2/hello_world

paths:
  /ping: # The URL path of the API will be /v2/hello_world/ping
    get:
      summary: Ping the API
      operationId: ping
      responses:
        "200": # For simplicity, we only define the 200 response. In real world, you should define all possible responses, such as 4xx, 5xx, etc.
          $ref: "#/components/responses/PongOK"

components:
  responses:
    PongOK:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/BaseResponse" # Inherit from BaseResponse
              - properties:
                  data:
                    $ref: "#/components/schemas/Pong" # The `data` property contains the actual `Pong` we want to return

  schemas:
    BaseResponse: # Every response should inherit from BaseResponse
      properties:
        message:
          description: message returned by server side if there is any
          type: string

    Pong:
      type: string
      example: Pong
